services:
 cassandra:
   image: cassandra:latest
   container_name: cassandra-container
   ports:
     - "9042:9042"
   environment:
     - CASSANDRA_START_RPC=true
   volumes:
     - cassandra_data:/var/lib/cassandra